#!/usr/bin/env bash

# Brew
brew update
brew upgrade

# Install core utils, Mac OS X is outdated
brew install coreutils
brew install findutils
brew install zsh
brew install neovim/neovim/neovim

# Git
brew install git

# Tmux + dependency
brew install tmux
# brew install reattach-to-user-namespace
# brew install ctags
# brew install ack
# brew install tree
# brew install ctags-exuberant

# Dev tools/languages
brew install go
brew install rbenv
brew install ruby-build
brew install node

# Databases
## PSQL
# brew install postgres --no-python
# initdb /usr/local/var/postgres -E utf8
## Redis
# brew install redis

# Native apps
brew tap phinze/homebrew-cask
brew install brew-cask

function installcask() {
    brew cask install "${@}" 2> /dev/null
}

installcask dropbox
installcask virtualbox
installcask google-chrome
installcask vlc
installcask sizeup
installcask hip-chat
installcask sparrow
installcask lastfm
installcask caffeine
installcask the-unarchiver
installcask rdio
brew install sequel-pro

brew clean
