#!/bin/sh

# load global xinit scripts
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

xset s off
xautolock -time 5 -locker slock -secure &

urxvtd --quiet --fork #--opendisplay

gpg-connect-agent "/bye" &

# https://wiki.archlinux.org/index.php/Java#Non-reparenting_window_managers
export _JAVA_AWT_WM_NONREPARENTING=1

# set a background
~/bin/wallpaper

# systray
(cd ~/.xmonad && stack exec taffybar &)


# window manager
exec xmonad
