#!/bin/sh

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

xset s 600 # 10 minutes to lock
xss-lock --quiet slock &

urxvtd --quiet --fork #--opendisplay

# https://github.com/knopwob/dunst/issues/238 (and from pbrisbin's dotfiles)
eval $(dbus-launch --sh-syntax --exit-with-session)

# set a background
~/bin/wallpaper

# systray, vol widget
trayer --edge top --align right --SetDockType true --SetPartialStrut True --expand True \
  --width 5 --height 20 --transparent true --tint 0x000000 &
pnmixer &

# window manager
exec xmonad
