# include local paths in PATH before system paths
if [[ $PATH != *"$HOME/.local/bin"* ]]; then
  export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
fi
# TODO do I need to add /var/lib/flatpak/exports/share to PATH ?

# Load zsh module config files
for config_file ($HOME/.config/zsh/**/*.zsh) source $config_file
