[General]
EnableNetworkConfiguration=true

[Network]
NetworkResolvingService=resolvconf
# Sometimes on, sometimes off. Mostly on these days, ocassionally needs to be
# turned off on some networks, so left here as a reminder.
EnableIPv6=true
