resolver: lts-6.26

packages:
  - "."
  - "vendor/taffybar"

extra-deps:
  - X11-1.8
  - X11-xft-0.3.1
  - directory-1.2.7.1
  - gtk-traymanager-0.1.6
  - taffybar-0.4.6
  - xmonad-0.13
  - xmonad-contrib-0.13
