resolver: lts-8.0

packages:
  - "."
  #- "./vendor/taffybar"

extra-deps:
  - X11-xft-0.3.1
  #- dbus-0.10.12
  #- gtk-0.13.9
  #- gtk-traymanager-0.1.6
  #- gtk-traymanager-0.1.6
  - xmonad-contrib-0.13
  #- libxml-sax-0.7.5
