#!/bin/sh
#
# Start with https://wiki.archlinux.org/index.php/Installation_guide
#
# After booting the Arch install media, run /installer/setup
set -e

setup_base_dir=$(dirname $0)
. "${setup_base_dir}/setup_scripts/shared.sh"

console_font="LatArCyrHeb-19"

############### PRE-SETUP ##################

# modern laptop screen and boot media kernel mode == teeeeeensy fonts
setfont "${console_font}"

############### MAIN SETUP ##################

"${setup_base_dir}/setup_scripts/packages.sh"
"${setup_base_dir}/setup_scripts/home.sh"
"${setup_base_dir}/setup_scripts/mullvad.sh"
"${setup_base_dir}/setup_scripts/systemd.sh"

echo "== [TODO CHECK FEDORA DEFAULTS] Symlink systemd-resolve resolv.conf"
# https://wiki.archlinux.org/title/Systemd-resolved#DNS
#rm /mnt/etc/resolv.conf
#ln -sf /run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf

# mullvad config
mullvad relay set tunnel-protocol wireguard

echo "==== enabling systemd units"
